### ISSUE TITLE
支持哪个版本啊？我在学习里也看不到什么答案啊，不知道加载成功没

### ISSUE THREAD

**Issue by supergming** [Xposed-Modules-Repo/xyz.xfqlittlefan.ciwong.hello#1]

**Comment by xfqwdsj** [comment]
抱歉 我使用的是 v3.54.780 我近期会做更新适配 最多2天
在习习向上设置中可以找到一个 HelloCiwong 设置就是加载成功了

**Comment by xfqwdsj** [comment]
经测试 HelloCiwong 1.1.1 可在习习向上 v3.57.788 上正常使用

**Comment by supergming** [comment]
> 经测试 HelloCiwong 1.1.1 可在习习向上 v3.57.788 上正常使用

这就尴尬了，我以为是xuexiqiangguo呢。打扰了，告辞
